import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/nav-bar";
import { Toaster } from 'react-hot-toast';
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Beaver Scrubber",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-sans antialiased`}
      >
        <Toaster toastOptions={{
          duration: 5000
        }} />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
